### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by hjone72** [thejinx0r/DriveFS#2]
Hi,

I think the following two lines should be changed.
https://github.com/thejinx0r/DriveFS/blob/master/src/gdrive/Filesystem.cpp#L220
https://github.com/thejinx0r/DriveFS/blob/master/src/gdrive/Filesystem.cpp#L872

Currently they throw a `error: invalid use of ‘this’ in non-member function`. After replacing `this` with `account` cmake reported a successful build.

Thanks :)

**Comment by thejinx0r** [comment]
fixed with e95cda6a630281f1f056eda89d4ae8c8fa1c8bc8

Thanks!
