### ISSUE TITLE
Running for the first time

### ISSUE THREAD

**Issue by somerandom48** [thejinx0r/DriveFS#3]
Have successfully compiled and now trying to run using the supplied config edited for my machine but get this error 

> 2018-07-11 05:15:38,052 [T] [Account.cpp:108] Getting Account
> 2018-07-11 05:15:38,053 [F] [easylogging++.cc:2868] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
>     ======= Backtrace: =========
>     [1] ./DriveFS(+0x70638) [0x55a31c2a4638] 
>     [2] ./DriveFS(+0x70819) [0x55a31c2a4819] 
>     [3]  0x3ef20) [0x7f2f1745af20]:_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f2f1745af20]
>     [4] /usr/local/lib/libmongoc-1.0.so.0(+0x24063) [0x7f2f16d2b063] 
>     [5] /usr/local/lib/libmongoc-1.0.so.0(+0x24078) [0x7f2f16d2b078] 
>     [6]  0x30b) [0x7f2f16d2c71c]:_mongoc_client_new_from_uri+0x30b) [0x7f2f16d2c71c]
>     [7]  0x2d) [0x7f2f16d2c40f]:_client_new_from_uri+0x2d) [0x7f2f16d2c40f]
>     [8]  0x38) [0x7f2f185c5e48]:_noabi(_ZN8mongocxx7v_noabi6clientC2ERKNS0_3uriERKNS0_7options6clientE+0x38) [0x7f2f185c5e48]
>     [9] ./DriveFS(+0xe40c3) [0x55a31c3180c3] 
>     [10] ./DriveFS(+0x9d5b7) [0x55a31c2d15b7] 
>     [11]  0xe7) [0x7f2f1743db97]:_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f2f1743db97]
>     [12] ./DriveFS(+0x5fc3a) [0x55a31c293c3a] 

I see in the in your notes that a headless login is on the ToDo list so booted up a desktop gui version but when running via terminal still get this same error. Is there somewhere I can inject my google account settings?

Cheers,

**Comment by thejinx0r** [comment]
Is it possible that you don't have mongodb running?

**Comment by somerandom48** [comment]
I have mongodb running and can connect to it via mongo shell as well as hit it when I browse to localhost:27017. I have also tried adding the database argument when running DriveFS mongodb://localhost/ or mongodb://localhost:27017/ but no luck

**Comment by somerandom48** [comment]
What version of mongodb are you running? db version v3.2.20
What version of libmongoc are you using? mongo-c-driver-1.11.0
What os are you using? ubuntu 18.04

Is it possible for me to get remote access to the machine? Yes that would be fine, how would you like me to get those details to you?

**Comment by thejinx0r** [comment]
Ok. I might have an idea.
You can email the login info to thejinx0r atsym Gmail doot com

**Comment by thejinx0r** [comment]
libmongoc was obtained from somewhere else, not from ubuntu. this version was compiled against libssl1.0, but everything else was compiled with libssl-1.1.

This caused an issue with connecting to mongodb.
