### ISSUE TITLE
File system not updated

### ISSUE THREAD

**Issue by mcadam** [thejinx0r/DriveFS#6]
Hello,

I am still testing the drive, speeds are great, uploads are going well, no problem there but I am seeing a weird behaviour on updates I think.

To give you more context, I am running in a cluster there is one node that writes on the disk, upload some files.
On the other node I should see the files appearing after 5 minutes waiting on the next update.

Whats happening it looked it work sometimes but not all the time.

On the node uploading the file, I can go to the folder and see the new file using ls command no problem there. On the new node though, the file is not present, I checked the logs in mongodb and I can see an update command on the file missing:
```
2018-09-08T06:35:27.656+0000 I WRITE    [conn3] update DriveFS.GDriveData command: { q: { id: "1rhjqb64HMr4lUwjWlz3sESzXXzb46TYC" }, u: { $set: { kind: "drive#file", id: "1rhjqb64HMr4lUwjWlz3sESzXXzb46TYC", ...
```
If I restart the drive on that node then all the files appear on the file system.

Any ideas?

I am running the drive with those options:
```
 -f --fuse-allow-other --cache-disk-size=10240 --cache-size=2048 --max-concurrent-downloads=24
```

Thanks for your help, even though I have this issue again its very promising so far :)

**Comment by thejinx0r** [comment]
i pushed some new code. Can you give it a try. It's not been mission critical for me, but I think I found a whole in the logic that should fix it.

I also parameterized the refresh interval, so you can set it to lower to test it more quickly.

**Comment by mcadam** [comment]
I am having an error on compiling 

```
Scanning dependencies of target DriveFS
[ 58%] Building CXX object CMakeFiles/DriveFS.dir/src/main.cpp.o
[ 62%] Building CXX object CMakeFiles/DriveFS.dir/src/gdrive/File.cpp.o
[ 65%] Building CXX object CMakeFiles/DriveFS.dir/src/gdrive/Filesystem.cpp.o
[ 68%] Building CXX object CMakeFiles/DriveFS.dir/src/BaseAccount.cpp.o
[ 72%] Building CXX object CMakeFiles/DriveFS.dir/src/gdrive/Account.cpp.o
[ 75%] Building CXX object CMakeFiles/DriveFS.dir/src/gdrive/FileIO.cpp.o
/app/src/main.cpp: In function 'int main(int, char**)':
/app/src/main.cpp:257:45: error: 'DriveFS::Filesystem' has not been declared
     struct fuse_lowlevel_ops ops = DriveFS::Filesystem::getOps({});
                                             ^~~~~~~~~~
make[2]: *** [CMakeFiles/DriveFS.dir/build.make:76: CMakeFiles/DriveFS.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/DriveFS.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by mcadam** [comment]
Changed it back to 
```-    struct fuse_lowlevel_ops ops = DriveFS::Filesystem::getOps({});
+    struct fuse_lowlevel_ops ops = DriveFS::getOps();```
and could compile again, is this ok?

**Comment by mcadam** [comment]
My bad I renamed the new option `refresh_interval` to `refresh-interval` to be consistent with the format of the other options and forgot to change
```
-    account.setRefreshInterval(vm["refresh_interval"].as<int>());
+    account.setRefreshInterval(vm["refresh-interval"].as<int>());
```

Now its running again, will keep you posted if I still any update issues.

Thanks

**Comment by mcadam** [comment]
Hello,

Don't forget to update that also to rename the option
```
-    account.setRefreshInterval(vm["refresh_interval"].as<int>());
+    account.setRefreshInterval(vm["refresh-interval"].as<int>());
```

So I've had the new code running for a day now, and I am again missing some new files not appearing on the other drive. It was working fine for a while but now I have to restart the drive to see the new files appearing on the file system.

**Comment by thejinx0r** [comment]
Good catch on the refrfesh_initerval.

Also, it might not have updated the new folder if a file had moved.
Would that make sense?

Anyways, I'll have to keep looking later and continue refactoring.

**Comment by thejinx0r** [comment]
By move, I meant move a file from one folder to another, which is not the case here.

There's one more thing I can try later.

How often were you having the problem?
Or is it sporadic and random now?

**Comment by mcadam** [comment]
Pretty hard to say, I thought maybe it was happening when I filled up the cache and maybe it was messing with things, but does not look like it, just after a while there are some files not appearing, let me try to add new ones and see if they appear now

**Comment by thejinx0r** [comment]
For the missing files, do you see it in the mongo log?

**Comment by mcadam** [comment]
I am not sure, I can see some new files appearing in the disk but dont find any logs with their names in Mongo, not sure Mongo logs all the time when creating new file the name, only on updates?

So after running it for a few days, I can see some new files appearing fine and some others not. I can see on one side, "Successfully uploaded" but not appearing on the other disk while sometimes working fine.

For now I need to restart the disk and then the missing ones appears.

**Comment by mcadam** [comment]
Hi,

I think the issue is when there are multiple updates in the same `changes` query on the drive, if i get one update at a time per `changes` query I think the files are appearing ok.
Not 100% sure but maybe that helps for your investigation?

**Comment by thejinx0r** [comment]
Hi mcadam, I added an extra function call to invalidate the entry.
If that doesn't work, I'll try uploading 1k files to see how many are missed.

**Comment by mcadam** [comment]
Thanks will try to compile the new version and deploy that to my cluster and give you some feedback in the next few days.

Thanks again for your work, already a great tool :)

**Comment by mcadam** [comment]
Hello,

After using the new version for a while, it's still not getting every updates, still need to restart the drives to get updates on some of the files. I think that version I might even get less updates, but couldn't say for sure.

**Comment by mcadam** [comment]
I think when there is a creation of a new directory involved it doesn't work, it seems that new files added to existing directories are appearing fine but if there is a new directory in which the new file is going then it doesn't work?
Not sure about that, just a thought from what I can see.

**Comment by mcadam** [comment]
Yeah I don't know, I just created a file on one drive, then waited for the next update on a different drive, I can see the token increasing so there was some update events in there but the file is not appearing, looks pretty random.

**Comment by thejinx0r** [comment]
It should be fixed now, but please give it a try

**Comment by mcadam** [comment]
Cool thanks will let you know if the next couple days how it goes, thanks again for your work, really appreciated 👍

**Comment by mcadam** [comment]
Hello, just to let you know it seems to be going very well on updates now, will let you know again in a week if we can close this.

**Comment by thejinx0r** [comment]
Great!
I'm glad to hear.

**Comment by mcadam** [comment]
Hey, forgot to got back to you but looking good now so closing this one :)
